"""Renders the app's icons (assets/icons/*.svg) to transparent PNGs and embeds them in src/ui/icon_data.h.

  python tools/make_icons.py

The icons are drawn white on a transparent background, so the app can tint them (grey at rest, teal on hover).
settings.svg is the "settings" gear of Google's Material Icons (Apache License 2.0), see assets/icons/LICENSE-material-icons.txt.
"""
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "assets" / "icons"
SIZE = 128                      # px; the app shows it at ~20-32 px, so this stays sharp on high-DPI screens

names = []
out = ["// Generated by tools/make_icons.py from assets/icons/*.svg. Do not edit.", "#pragma once", "", "namespace gm {", ""]
for svg in sorted(ICONS.glob("*.svg")):
    text = svg.read_text(encoding="utf-8")
    doc = pymupdf.open(stream=text.encode("utf-8"), filetype="svg")
    page = doc[0]
    scale = SIZE / page.rect.width
    pix = page.get_pixmap(matrix=pymupdf.Matrix(scale, scale), alpha=True)
    png = pix.tobytes("png")
    (ICONS / f"{svg.stem}.png").write_bytes(png)
    corner = pix.pixel(0, 0)           # (r, g, b, a): a must be 0, or the icon is not transparent
    assert corner[3] == 0, f"{svg.name}: background is not transparent"
    name = "k" + "".join(p.capitalize() for p in svg.stem.split("-")) + "Png"
    names.append(name)
    out.append(f"// {svg.stem}: {pix.width}x{pix.height}, {len(png)} bytes")
    out.append(f"inline const unsigned char {name}[] = {{")
    for i in range(0, len(png), 24):
        out.append("    " + ", ".join(f"0x{b:02x}" for b in png[i:i + 24]) + ",")
    out.append("};")
    out.append(f"inline constexpr unsigned long {name}Size = sizeof({name});")
    out.append("")
    print(f"{svg.name}: {pix.width}x{pix.height}px, {len(png)} bytes, corner alpha {corner[3]}")
out.append("}  // namespace gm")
(ROOT / "src" / "ui" / "icon_data.h").write_text("\n".join(out) + "\n", encoding="utf-8")
